### ISSUE TITLE
Add possibility to rename the target

### ISSUE THREAD

**Issue by isbm** [isbm/mezzotint#20]
Add possibility to rename target path.
E.g. `/usr/bin/emacs-nox` to `/usr/bin/emacs`

```yaml
target:
  - /usr/bin/emacs-nox -> /usr/bin/emacs
```

**Comment by isbm** [comment]
Decided on script hooks instead:

```yaml
before: |
    echo "before anything" > /tmp/before.txt

after: |
    echo "after calculation, before applying the state" > /tmp/after.txt
```
